version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "3300:3300"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/magicMovers
      - PORT=3300 
    networks:
      - app-network
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
